// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-courses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_courses_default = defineTool({
  name: "list_courses",
  title: "List Canvas courses",
  description: "List the signed-in teacher's Canvas courses via the connected Canvas account. Requires the user to have connected Canvas in Allen.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabaseUrl = process.env.SUPABASE_URL;
    if (!supabaseUrl) {
      return { content: [{ type: "text", text: "Missing SUPABASE_URL" }], isError: true };
    }
    const res = await fetch(`${supabaseUrl}/functions/v1/get-canvas-courses`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ctx.getToken()}`
      },
      body: JSON.stringify({})
    });
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Canvas courses request failed (${res.status}): ${text}` }],
        isError: true
      };
    }
    let parsed = text;
    try {
      parsed = JSON.parse(text);
    } catch {
    }
    return {
      content: [{ type: "text", text: typeof parsed === "string" ? parsed : JSON.stringify(parsed, null, 2) }],
      structuredContent: typeof parsed === "object" && parsed !== null ? parsed : { raw: text }
    };
  }
});

// src/lib/mcp/tools/list-assignments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_assignments_default = defineTool2({
  name: "list_assignments",
  title: "List assignments in a Canvas course",
  description: "List assignments for a specific Canvas course belonging to the signed-in teacher. Provide the numeric Canvas course id.",
  inputSchema: {
    courseId: z.union([z.string(), z.number()]).describe("The Canvas course id (as returned by list_courses).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ courseId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabaseUrl = process.env.SUPABASE_URL;
    if (!supabaseUrl) {
      return { content: [{ type: "text", text: "Missing SUPABASE_URL" }], isError: true };
    }
    const res = await fetch(`${supabaseUrl}/functions/v1/get-canvas-assignments`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ctx.getToken()}`
      },
      body: JSON.stringify({ courseId: String(courseId) })
    });
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Canvas assignments request failed (${res.status}): ${text}` }],
        isError: true
      };
    }
    let parsed = text;
    try {
      parsed = JSON.parse(text);
    } catch {
    }
    return {
      content: [{ type: "text", text: typeof parsed === "string" ? parsed : JSON.stringify(parsed, null, 2) }],
      structuredContent: typeof parsed === "object" && parsed !== null ? parsed : { raw: text }
    };
  }
});

// src/lib/mcp/tools/list-assignments-needing-grading.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_assignments_needing_grading_default = defineTool3({
  name: "list_assignments_needing_grading",
  title: "List assignments needing grading",
  description: "List all assignments across the signed-in teacher's Canvas courses that currently have submissions needing grading.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabaseUrl = process.env.SUPABASE_URL;
    if (!supabaseUrl) {
      return { content: [{ type: "text", text: "Missing SUPABASE_URL" }], isError: true };
    }
    const res = await fetch(`${supabaseUrl}/functions/v1/get-all-assignments-needing-grading`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ctx.getToken()}`
      },
      body: JSON.stringify({})
    });
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Request failed (${res.status}): ${text}` }],
        isError: true
      };
    }
    let parsed = text;
    try {
      parsed = JSON.parse(text);
    } catch {
    }
    return {
      content: [{ type: "text", text: typeof parsed === "string" ? parsed : JSON.stringify(parsed, null, 2) }],
      structuredContent: typeof parsed === "object" && parsed !== null ? parsed : { raw: text }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fnxbysvezshnikqboplh";
var mcp_default = defineMcp({
  name: "allen-canvas-mcp",
  title: "Allen for Canvas",
  version: "0.1.0",
  instructions: "Tools for the Allen for Canvas grading assistant. Use `list_courses` to see the signed-in teacher's Canvas courses, `list_assignments` to browse assignments in one course, and `list_assignments_needing_grading` to find submissions that still need grading.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_courses_default, list_assignments_default, list_assignments_needing_grading_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
