// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnxbysvezshnikqboplh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZueGJ5c3ZlenNobmlrcWJvcGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTEyMTEsImV4cCI6MjA2Mzc4NzIxMX0.hCtaOZtHplGlUNFpEIyyXDvOCLmR7bgLfTzaMYdKSVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);